#! /usr/bin/bash

# Example config
# cp -r ~/.config/ ./ & 
# echo -e " \xE2\x9C\x94" & 

# Fonts
# cp -r ~/.fonts/ ./ & 
echo -e "Fonts \xE2\x9C\x94" & 

# Bspwm config
cp -r ~/.config/bspwm/ ./.config/ & 
echo -e "Bspwm \xE2\x9C\x94" & 

# Neofetch config
cp -r ~/.config/neofetch/ ./.config/ & 
echo -e "Neofetch \xE2\x9C\x94" & 

# NeoVim config
cp -r ~/.config/nvim/ ./.config/ & 
echo -e "NeoVim \xE2\x9C\x94" & 

# Picom config
cp -r ~/.config/picom/ ./.config/ & 
echo -e "Picom \xE2\x9C\x94" & 

# Polybar config
cp -r ~/.config/polybar/ ./.config/ & 
echo -e "Polybar \xE2\x9C\x94" & 

# Rofi config
cp -r ~/.config/rofi/ ./.config/ & 
echo -e "Rofi \xE2\x9C\x94" & 

# Sxhkd config
cp -r ~/.config/sxhkd/ ./.config/ & 
echo -e "Sxhkd \xE2\x9C\x94" & 

# Xfce4-Terminal config
cp -r ~/.config/xfce4/ ./.config/ & 
echo -e "Xfce4 Terminal \xE2\x9C\x94" & 

# Bash config
cp -r ~/.bashrc ./.config/ & 
echo -e "Bash config \xE2\x9C\x94" & 

