#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d dev dev dev web web tool tool rest 

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Auto-Start Programms:
picom --config $HOME/.config/picom/picom.conf & 
xrandr --output DP-4 --rotate normal &
xrandr --output DP-2-2 --rotate right &
polybar &
xset dpms 0 0 0 && xset s noblank  && xset s off &
feh --bg-scale /home/julius/Background-debian.jpg
setxkbmap -option caps:escape
