#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

if [[ $(xrandr -q | grep 'DP-2-1 connected') && $(xrandr -q | grep 'DP-2-3 connected') ]]; then
    # Your commands to execute when both conditions are true
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output DP-2-1 --mode 2560x1440 --rotate normal --left-of eDP-1 --output DP-2-3 --mode 3440x1440 --rotate normal --left-of DP-2-1

    bspc monitor eDP1 -d I II III
    bspc monitor DP-2-1 -d IV V VI VII
    bspc monitor DP-2-3 VIII IX X
else
    bspc monitor eDP1 -d I II III IV V
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Auto-Start Programms:
picom --config $HOME/.config/picom/picom.conf & 
polybar &
feh --bg-scale /home/julius/Pictures/Background-debian.jpg
